<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2019/2/28
 * Time: 17:05
 */

namespace App\Http\Controllers\Admin;

use App\Model\FoodModel;
use Illuminate\Http\Request;
use DB;

class FoodController extends BaseController{

    public function getList(Request $request){
        $this->markPage();
        $store_id = $request->get('store_id', 0);
        $keyword = $request->get('keyword', null);
        $store_name = null;

        $builder = DB::table('food')
            ->leftJoin('store', 'food.store_id', '=', 'store.id');

        if ($store_id != 0){
            $store_name = DB::table('store')->where('id', $store_id)->value('name');
            if (!$store_name){
                return "没有找到该店家";
            }
            $builder->where('store_id', $store_id);
        }

        if ($keyword){
            $like_str = sprintf("%%%s%%", $keyword);
            $builder->where('food.name', 'like', $like_str);
        }

        $list = $builder->select(['food.*', 'store.name as store_name', 'store.id as store_id'])
            ->orderBy('status', 'desc')
            ->orderBy('id', 'asc')
            ->paginate(env("PAGE_SIZE", 10));

        return view('Admin.food.list',compact('list', 'store_id', 'store_name', 'keyword'));
    }

    public function getForm(Request $request){
        $store_id = $request->get('store_id', 0);
        $id = $request->get('id', 0);

        if ($store_id == 0){
            return "请先选择需要添加餐点的店家";
        }

        $data = [];
        if ($id != 0){
            $data = DB::table('food')
                ->where('id', $id)
                ->first();
        }

        return view('Admin.food.form', compact('data', 'store_id'));
    }

    public function postForm(Request $request){
        $data = $request->all();

        $foodModel = new FoodModel();
        if ($err = $foodModel->validator($data)->first()){
            return $this->ajaxFail("", $err);
        }

        $id = $data['id'];
        unset($data['id']);

        if ($id != 0){
            $op = "修改";
            $success = DB::table('food')->where('id', $id)->update($data);
        }else{
            $op = "新增";
            $success = DB::table('food')->insert($data);
        }

        if ($success){
            return $this->ajaxSuccess("", "{$op}成功", $this->getMarkPage()."?store_id={$data['store_id']}");
        }
        return $this->ajaxFail("", "{$op}失败");
    }

    public function postStatus(Request $request)
    {
        return parent::postStatus($request); // TODO: Change the autogenerated stub
    }
}